### ISSUE TITLE
The products of the same type can be added to Cart multiple times

### ISSUE THREAD

**Issue by BatyrSeven** [imustafin/innopolis-express#4]
**Expected behavior:** The products of the same type **cannot** be added to Cart multiple times. Instead, the quantity of the product is increased.
**Actual behavior:** The products of the same type **can** be added to Cart multiple times. The quantity of the product is not changing.

The error is in the [method `addProduct`](https://github.com/imustafin/innopolis-express/blob/master/MVP/app/src/main/java/mfq/com/refooddelivery2/models/Cart.java#L26) of the [class `Cart`](https://github.com/imustafin/innopolis-express/blob/master/MVP/app/src/main/java/mfq/com/refooddelivery2/models/Cart.java).

The bug was found during the implementation of unit tests

**Comment by imustafin** [comment]
Fixed by 6079f2bc675e9f6695cb94d61a6fe7e6804c49ec
